2023-05-09 - Added info & Fxix
Added text about updating Oobabooga.

For some reason aria2c needs to be run with "--disable-ipv6" sometimes to get things to work properly. This is a very strange issue... I couldn't download anything, for example.

Error: Download aborted. Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.
See: https://github.com/aria2/aria2/issues/1549